### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by hbhoyar** [HarryK24/CW-pytorch#2]
Hey, even after adverserial attack, the panda image is being classified as panda. Can you help regarding this?

PS - I ran whole notebook as it is after uploading data

**Comment by WinddyAkoky** [comment]
I am same as you. I think the codes are wrong

**Comment by hbhoyar** [comment]
You have to increase c value in this to 10 or 100
```
images = cw_l2_attack(model, images, labels, targeted=False, c=0.1)
```
